service: 
    name: trigger-alert-test
provider:
 name: aws
 runtime: nodejs8.10
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1

functions:
    sendAlert: 
        handler: index.handler
